# action.yml
name: 'testresults'
description: 'Format test results'
inputs:
  xunit:
    description: 'xunit test results file'
    required: true
  html:
    description: 'Output HTML file'
    required: true
outputs:
  passes:
    description: 'Number of passing tests'
  failures:
    description: 'Number of failing tests'
  skipped:
    description: 'Number of skipped tests'
  summary:
    description: 'Summary of test results'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '--xunit'
    - ${{ inputs.xunit }}
    - '--html'
    - ${{ inputs.html }}
