# action.yml
name: 'testresults'
description: 'Format test results'
inputs:
  xunit:
    description: 'xunit test results file'
    required: true
  html:
    description: 'Output HTML file'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '--xunit'
    - ${{ inputs.xunit }}
    - '--html'
    - ${{ inputs.html }}
